# Generated by Django 5.0.6 on 2024-05-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_postcomment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='api.post'),
        ),
    ]
