# Generated by Django 5.0.6 on 2024-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_postcomment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post_id',
            field=models.IntegerField(),
        ),
    ]
