# Generated by Django 4.2.13 on 2024-05-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_postcomment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='commentor',
            field=models.TextField(),
        ),
    ]
